Add public log channel
Retro-Rewind-Team/wfc-bot pull request #1
Opened 2024-08-21 04:05 UTC by LamiLemmy

Also adds hidden reason to all commands, which is not showed in the public log.
I don't know JS this is probably horrible.

2024-08-22 06:28 UTC, ppebb requested changes

2024-08-22 06:28 UTC, ppebb commented on config.example.json
What's with the logs channel being an array here? No changes were made to the logic for uploading the logs to every channel in the array, so which is it meant to be?

This can either be reverted to a single string field or the logic for sending logs can be updated.

2024-08-22 13:10 UTC, LamiLemmy commented on config.example.json
Oh wth, this is definitely an error, don't know what's up here

2024-08-23 01:59 UTC, ppebb approved these changes

2024-08-23 01:59 UTC, merged